apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-endpoint
  namespace: ml-scraper
data:
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://$(NODE_IP):4317"
  OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
  OTEL_SERVICE_NAME: "scraper"